api_keys:
  binance: "Wn68OKrWIORk5UkcsQA8nPQTzUYlLgWycIflFCIa4bicwHN9aDMNQi14E2GwJgAt"
  binance_secret: "MHQzHHeAXsW5hCAT563unPbHD2O52WRykMkIWnLZNq011IiJ0a6Yru4hQaMIWvtv"

risk_management:
  risk_per_trade: 0.01
  max_lot: 1.0

hyperparameters:
  leverage: 100
  candle_size: 15
  historical_period_days: 365

telegram:
  bot_token: "8169949432:AAGS7CvD298BKhTasFdg1AZzhWc8GNDzwnk"
  chat_id: "8465614004"
